main: ${project.groupId}.${project.artifactId}

name: ${project.artifactId}
version: ${project.version}
author: Bearless_
softdepend: [ LuckPerms ]

commands:
  lobbymanager-spawn:
    aliases: [lm-spawn, spawn]
  lobbymanager-setspawn:
    aliases: [lm-setspawn, setspawn]
  lobbymanager-reload:
    aliases: [lm-reload]