main: fr.bearless.lobbymanager.LobbyManager

name: LobbyManager
version: 2
author: Bearless

commands:
  lobbymanager-reload:
    aliases: lm-reload
    description: Reload the configuration file.
  lobbymanager-spawn:
    aliases: [lm-spawn, spawn]
    description: Send the player the the Spawn/Lobby.
  lobbymanager-setspawn:
    aliases: [lm-setspawn, setspawn]
    description: Set the Spawn Location where the Player are.