main: ${project.groupId}.${project.artifactId}

name: ${project.name}
version: ${project.version}
author: Bearless_
softdepend: [ LuckPerms ]

commands:
  lobbymanager:
    aliases: lm
  spawn:
  setspawn: