#    _          _     _           __  __
#   | |    ___ | |__ | |__  _   _|  \/  | __ _ _ __   __ _  __ _  ___ _ __
#   | |   / _ \| '_ \| '_ \| | | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
#   | |__| (_) | |_) | |_) | |_| | |  | | (_| | | | | (_| | (_| |  __/ |
#   |_____\___/|_.__/|_.__/ \__, |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|
#                           |___/                          |___/           
# By Bearless
# Version: 1.0

# All the event that concerns a block
World-Event:
  # When a player try to break a block
  block-break:
    # The permission required to break block
    permission: lobbymanager.block.break
    # Message send to the player if he don't have the permission
    permission-message: "&cHeyy why are you trying to destroy the server ?"