#    _          _     _           __  __
#   | |    ___ | |__ | |__  _   _|  \/  | __ _ _ __   __ _  __ _  ___ _ __
#   | |   / _ \| '_ \| '_ \| | | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
#   | |__| (_) | |_) | |_) | |_| | |  | | (_| | | | | (_| | (_| |  __/ |
#   |_____\___/|_.__/|_.__/ \__, |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|
#                           |___/                          |___/           
# By Bearless
# Version: 1.0
#
#
# LobbyManager Placeholder:
#
# %player% --> return the name of the player.
#
#

usage-message:
  reload: "&c&lIncorrect Usage: &c/lm-reload &c&lor &c/lobbymanager-reload" #Message when you do the wrong reload command.

server:
  disable_default_join_message: true #Disable the default join message "Bearless joined the game".
  disable_default_quit_message: true #Disable the default quit message "Bearless quit the game".

  custom_join_message: "&a%player% &ejoin the lobby!" #Replace the default join message by a custom one.
  custom_quit_message: "&a%player% &equit the lobby!" #Replace the default quit message by a custom one.

world:
  disable_pvp: true #Prevent players fromo pvp.

  block-break:
    enable: true #Disable the ability for the players to break block.
    permission: "lobbymanager.block.break" #The permission needed to break block.
    permission-message: "&cSorry, but you can't break block." #The message who appear when a player try to break a block without the permission.

  block-place:
    enable: true #Disable the ability for the players to place block.
    permission: "lobbymanager.block.place" #The permission needed to place block.
    permission-message: "&cSorry, but you can't place block." #The message who appear when a player try to place a block without the permission.

  disable-entity-spawn: true #Disable the spawn of entity (Passive and Aggressive) like (Pig, Creeper, Zombie, Cow etc...).
  disable-weather-change: true #Disable the change of the weather.

  enable_join_player_spawn_loc: true #enable or disable the custom spawn for player while joining the server.
  spawn_world_name: "world" #The name of the world where the spawn will be set.
  spawn_X: 0 #The X position of the custom spawn.
  spawn_Y: 65 #The Y position of the custom spawn.
  spawn_Z: 0 #The Z position of the custom spawn.
  spawn_Yaw: 180 #The YAW position of the custom spawn.
  spawn_Pitch: 0 #The PITCH position of the custom spawn.

  teleport_onFall: 5 #When a player falls into the void, that position Y will be the point where the player will be teleported to the custom spawn.

player:
  disable_fall_damage: true #Preventing player from taking fall damage.
  disable_food_loss: true #Preventing player from lost food.

  player_health_level: 20 #Set the health of the player when joining the server.
  player_food_level: 20 #Set the food of the player when joining the server.

  enable_player_gamemode: true #Enable or Disable the gamemode of the player when joining the server.
  set_player_gamemode: "adventure" #The gamemode will be set to the player when joining the server.
  #available Gamemode (creative, survival, adventure, spectator) *Case non-sensitive.

  tablist_header: "&aThis is a header\n &ewith a new lines" #Set the header of the tablist. TIP: type "\n" to get a new line.
  tablist_footer: "&6This is a footer\n &2with a new lines" #Set the footer of the tablist. TIP: type "\n" to get a new line.

commands: #List of all the Permission/Message of all the plugin command.
  reload:
    permission: "lobbymanager.commands.reload" #The permission to do /lm-reload.
    permission-message: "&cYou don't have the required permission." #The message will be sent to the player who perform the command without the right permission.
    reload-message: "&aThe configuration file have been reloaded." #The message send when the command successfully done.
  spawn:
    spawn_message: "§aYou have been teleported to the spawn."