name: Hub
version: 1.0
author: Bearless
main: fr.bearless.hub.Main

commands:
  gm:
    description: "Permet de changer de Mode de Jeux rapidement."
  spawn:
    aliases: lobby
    description: "Permet de se téléporter au spawn."