name: LobbyManager
version: 1.1
author: Bearless
main: fr.bearless.lobbymanager.Main

commands:
  lobbymanager-reload:
    aliases: lm-reload
    description: Reload the configuration file.
  lobbymanager-spawn:
    aliases: [lm-spawn, spawn]
    description: Send the player the the Spawn/Lobby.