name: LobbyManager
version: 1.0
api-version: 1.8.8
author: Bearless
main: fr.bearless.lobbymanager.Main

commands:
  lobbymanager-reload:
    aliases: lm-reload
    description: Reload the configuration file